name: bug report
description: Create a report to help us improve
labels: [bug]
body:
- type: markdown
  attributes:
    value: "**Please describe the bug**"
- type: textarea
  id: reproduce_steps
  attributes:
    label: "Steps to reproduce"
    value: "Steps to reproduce the behavior:\n\n      1. Go to &#39;...&#39; \n      2. Click on &#39;....&#39; \n      3. Scroll down to &#39;....&#39;\n      4. See error\n      ";

